dist: bionic
sudo: required
language: c

branches:
  only:
  - master

cache:
  apt: true
  directories:
  - $HOME/.opam

addons:
  apt:
    packages:
    - cvc3
env:
  global:
  - OPAMYES="true"
  - OPAMJOBS="2"
  matrix:
  - OCAML=4.07.1

before_install:
- sudo curl -sL https://github.com/ocaml/opam/releases/download/2.0.6/opam-2.0.6-x86_64-linux -o /usr/bin/opam
- sudo chmod 755 /usr/bin/opam
# CVC 1.6 doesn't work with why 0.87
- sudo curl -sL http://cvc4.cs.stanford.edu/downloads/builds/x86_64-linux-opt/cvc4-1.4-x86_64-linux-opt -o /usr/bin/cvc4
- sudo chmod 755 /usr/bin/cvc4
# - wget http://wwwlehre.dhbw-stuttgart.de/~sschulz/WORK/E_DOWNLOAD/V_2.3/E.tgz
- opam init --disable-sandboxing -c $OCAML
- opam switch set $OCAML
- eval $(opam env)

install:
- travis_wait opam install --deps-only -d -t .
# - travis_wait opam install menhir why3.1.2.1 alt-ergo.2.3.0 # coq.8.10.2
- why3 config --detect

script:
- set -e
- dune build
- dune runtest
- make examples
