The files:

src/ecIo.ml
src/ecLocation.ml
src/ecPException.ml
src/ecProvers.ml
src/ecUtils.ml
src/ecIo.mli
src/ecLocation.mli
src/ecPException.mli
src/ecProvers.mli
src/ecUtils.mli

were derived from the EasyCrypt tool (https://www.easycrypt.info/) and
are copyright:

  Copyright (c) - 2012-2015 - IMDEA Software Institute and INRIA
  Distributed under the terms of the CeCILL-C license

  http://www.cecill.info/licences/Licence_CeCILL-C_V1-en.txt
